site_name: Digital contact tracing
nav:
    - Home: index.md
    - load graphs: loadTemporalGraph.md
    - DigitalContactTracing : DigitalContactTracing.md
    - FunctionContinuousModel : functionsContinousModel.md
    - SystemDefinition : systemDefinition.md
theme: readthedocs


